Fix windows build
emilydolson/python-phylogeny-tracker pull request #55
Opened 2023-11-26 04:24 UTC by emilydolson

Attempting to fix #54

2023-11-26 08:14 UTC, emilydolson commented
It works! Had to gut optional _throw a bit (we should eventually try to add back the functionality I just removed), but I'd say it's functional.

If you're good with removing NumPy as a dependency, feel free to merge this. Also happy to be convinced to keep numpy

2023-11-27 04:58 UTC, mmore500 commented
I suspect that numpy-data-as-taxon-info is a potential use case. I'm thinking of how DEAP has a whole section on Numpy genetic representations <https://deap.readthedocs.io/en/master/tutorials/advanced/numpy.html>

If reverting back NumPy breaks tests, though, let's axe it.

2023-11-27 23:19 UTC, emilydolson commented
How does this look to you? It tests the numpy functionality without actually adding it as a dependency or testing it in the wheels (where build systems get messier)

2023-11-27 23:29 UTC, mmore500 requested changes
👍 this setup seems like a good idea

If I’m reading the diffs right, we still need to uncomment numpy test cases and add the `nowheel` marker you created?

Here’s the syntax for that btw <https://docs.pytest.org/en/7.1.x/example/parametrize.html#set-marks-or-test-id-for-individual-parametrized-test>

Added a suggestion to pin numpy install on the test job. I think there’s an argument to be made either way (pin or track latest). The argument to pin being that (potentially very confusing) breakage would occur when you’re working on something unrelated and potentially cause a wild goose chase or annoyingly couple a task to unrelated maintenance issues.

(Pinning numpy directly doesn’t work well b/c wheels aren’t available across all python versions, hence oldest-supported-numpy).

2023-11-27 23:29 UTC, mmore500 commented on .github/workflows/ci.yml
> +        pip install numpy
```suggestion
        pip install oldest-supported-numpy==2023.10.25
```

2023-12-01 04:49 UTC, emilydolson commented
I believe the numpy test case is already be marked with the nowheel and running. Pinning numpy is good with me (although I think it should be less fragile in the test environment than in the wheel environment)

2023-12-01 17:47 UTC, mmore500 commented
Ah, I see that one of the tests is set up, put the other one together in f55acab. Merging!

2023-12-01 17:47 UTC, merged